Repository KingsburyLab/pyEQL, pull requests merged in 2023-11, with the labels that each got.

#72 Performance Improvements
  AUTHORS.md
  CHANGELOG.md
  setup.cfg
  src/pyEQL/__init__.py
  src/pyEQL/engines.py
  src/pyEQL/equilibrium.py
  src/pyEQL/solution.py
  src/pyEQL/utils.py
  tests/test_phreeqc.py
Labels: enhancement, release:patch

#73 Fix link in README to pyscaffold
  README.md
  docs/database.md
Labels: docs

#74 Restore duplicate log filtering
  CHANGELOG.md
  examples/pyeql_demo.ipynb
  src/pyEQL/logging_system.py
Labels: release:patch, fix, docs

#67 Replace autogenerate() with a Solution class method
  CHANGELOG.md
  presets/Ringers lactate.yaml
  presets/normal saline.yaml
  presets/rainwater.yaml
  presets/seawater.yaml
  presets/urine.yaml
  presets/wastewater.yaml
  src/pyEQL/functions.py
  src/pyEQL/solution.py
  tests/test_solution.py
Labels: enhancement, feature

#77 add python 3.12 to CI, readme
  .github/workflows/testing.yaml
  .github/workflows/upgrade_dependencies.yml
  README.md
Labels: housekeeping, pkg

#76 docs: update demo, add tutorial notebooks
  AUTHORS.md
  CHANGELOG.md
  CONTRIBUTING.md
  docs/contributing.md
  docs/examples.md
  docs/examples/.ipynb_checkpoints/pyEQL_demo_1-checkpoint.ipynb
  docs/examples/.ipynb_checkpoints/pyeql_demo-checkpoint.ipynb
  docs/examples/.ipynb_checkpoints/pyeql_tutorial_database-checkpoint.ipynb
  docs/examples/.ipynb_checkpoints/pyeql_tutorial_osmotic_pressure-checkpoint.ipynb
  docs/examples/.ipynb_checkpoints/speedup-checkpoint.ipynb
  docs/examples/pyEQL_demo_1.ipynb
  docs/examples/pyeql_demo.ipynb
  docs/examples/pyeql_tutorial_database.ipynb
  docs/examples/pyeql_tutorial_osmotic_pressure.ipynb
  docs/examples/speedup.ipynb
  docs/index.md
  docs/tutorials.md
Labels: docs

#78 D temp
  CHANGELOG.md
  src/pyEQL/activity_correction.py
  src/pyEQL/database/pyeql_db.json
  src/pyEQL/engines.py
  src/pyEQL/solute.py
  src/pyEQL/solution.py
  tests/test_activity.py
  tests/test_phreeqc.py
  tests/test_solute_properties.py
  tests/test_solution.py
Labels: enhancement, release:minor, feature

#80 Use IAPWS97 for speed; cache instance via utility function
  CHANGELOG.md
  src/pyEQL/activity_correction.py
  src/pyEQL/solution.py
  src/pyEQL/utils.py
  tests/test_utils.py
Labels: enhancement

#79 Miscellanous small enhancements
  CHANGELOG.md
  src/pyEQL/engines.py
  src/pyEQL/solution.py
  tests/test_solute_properties.py
  tests/test_solution.py
  tox.ini
Labels: enhancement, release:patch, housekeeping, pkg

#81 PHREQC engine enhancements
  CHANGELOG.md
  src/pyEQL/engines.py
  src/pyEQL/equilibrium.py
  src/pyEQL/functions.py
  tests/test_phreeqc.py
  tests/test_solution.py
Labels: enhancement

#82 equilibrate(): fix charge balancing bugs in Native and PhreeqC engines
  CHANGELOG.md
  src/pyEQL/engines.py
  src/pyEQL/solution.py
  tests/test_phreeqc.py
Labels: release:minor, fix

#83 Add tests for gibbs_mix and entropy_mix
  CHANGELOG.md
  docs/creating.md
  src/pyEQL/__init__.py
  src/pyEQL/functions.py
  tests/test_functions.py
  tests/test_osmotic_coeff.py
Labels: enhancement, breaking
