Repository KingsburyLab/pyEQL, pull requests merged in 2023-10, with the labels that each got.

#45 serialization and copy bugfixes and enhancements
  CHANGELOG.md
  src/pyEQL/solution.py
  tests/test_solution.py
Labels: enhancement, release:patch, fix, housekeeping

#46 Fix Solution serialization
  CHANGELOG.md
  setup.cfg
  src/pyEQL/solution.py
  src/pyEQL/utils.py
  tests/test_solution.py
Labels: dependencies, fix

#47 Solution: always sort components by amount
  CHANGELOG.md
  src/pyEQL/solution.py
  src/pyEQL/utils.py
Labels: enhancement

#48 Drop python 3.8 support
  .github/workflows/post-process.yml
  .github/workflows/testing.yaml
  .github/workflows/upgrade_dependencies.yml
  CHANGELOG.md
  README.md
  docs/conf.py
  setup.cfg
Labels: dependencies, pkg

#30 Solution: add print(), deprecate list_xxx methods
  CHANGELOG.md
  src/pyEQL/solution.py
  tests/test_phreeqc.py
  tests/test_solution.py
Labels: enhancement

#49 Documentation overhaul
  .github/workflows/testing.yaml
  .github/workflows/upgrade_dependencies.yml
  .gitignore
  AUTHORS.md
  CHANGELOG.md
  README.md
  docs/amounts.md
  docs/arithmetic.md
  docs/chemistry.md
  docs/class_solution.md
  docs/conf.py
  docs/contributing.md
  docs/creating.md
  docs/database.md
  docs/engines.md
  docs/examples.md
  docs/index.md
  docs/installation.md
  docs/internal.md
  docs/mixing.md
  docs/pyeql_demo.ipynb
  docs/quickstart.md
  docs/requirements.txt
  docs/serialization.md
  docs/tutorial.md
  docs/units.md
  docs/utilities.md
  examples/pyeql_demo.ipynb
  pyeql-demo.png
  src/pyEQL/engines.py
  src/pyEQL/functions.py
Labels: docs

#51 remove pyEQL.unit deprecation warning
  CHANGELOG.md
  src/pyEQL/__init__.py
Labels: release:minor, housekeeping, breaking

#65 Add utility method to format dictionary
  CHANGELOG.md
  src/pyEQL/utils.py
  tests/test_utils.py
Labels: feature
