Repository KingsburyLab/pyEQL, pull requests merged in 2024-09, with the labels that each got.

#182 Bugfix in get_total_amount; CHANGELOG for next version
  AUTHORS.md
  CHANGELOG.md
  src/pyEQL/solution.py
  src/pyEQL/utils.py
  tests/test_solution.py
  tests/test_utils.py
Labels: release:patch, fix

#188 pymatgen>=2024.9.10 updated after bugfix and conflict resolve
  .github/workflows/post-process.yml
  .github/workflows/testing.yaml
  .github/workflows/upgrade_dependencies.yml
  README.md
  docs/requirements.txt
  pyproject.toml
  tests/test_phreeqc.py
Labels: dependencies, github_actions

#190 database fixes
  .pre-commit-config.yaml
  CHANGELOG.md
  CITATION.cff
  docs/creating.md
  setup.py
  src/pyEQL/database/pyeql_db.json
  src/pyEQL/functions.py
  src/pyEQL/presets/Ringers lactate.yaml
  src/pyEQL/presets/normal saline.yaml
  src/pyEQL/presets/rainwater.yaml
  src/pyEQL/presets/seawater.yaml
  src/pyEQL/presets/urine.yaml
  src/pyEQL/presets/wastewater.yaml
  src/pyEQL/utils.py
  tests/test_activity.py
  tests/test_bulk_properties.py
  tests/test_debye_length.py
  tests/test_density.py
  tests/test_dielectric.py
  tests/test_effective_pitzer.py
  tests/test_equilibrium.py
  tests/test_functions.py
  tests/test_mixed_electrolyte_activity.py
  tests/test_phreeqc.py
  tests/test_salt_matching.py
  tests/test_solute.py
  tests/test_solution.py
  tests/test_volume_concentration.py
Labels: release:minor, fix

#191 modify pre-commit; run on all files
  .pre-commit-config.yaml
  .zenodo.json
  docs/examples/.ipynb_checkpoints/pyEQL_demo_1-checkpoint.ipynb
  docs/examples/.ipynb_checkpoints/pyeql_demo-checkpoint.ipynb
  docs/examples/.ipynb_checkpoints/pyeql_tutorial_database-checkpoint.ipynb
  docs/examples/.ipynb_checkpoints/pyeql_tutorial_osmotic_pressure-checkpoint.ipynb
  docs/examples/.ipynb_checkpoints/speedup-checkpoint.ipynb
  docs/examples/pyEQL_demo_1.ipynb
  docs/examples/pyeql_demo.ipynb
  docs/examples/pyeql_tutorial_database.ipynb
  docs/examples/pyeql_tutorial_osmotic_pressure.ipynb
  docs/examples/speedup.ipynb
  src/pyEQL/database/pyeql_db.json
  src/pyEQL/solution.py
  tests/conftest.py
Labels: housekeeping, pkg
