Repository KingsburyLab/pyEQL, pull requests merged in 2024-08, with the labels that each got.

#164 updated python-version line 48 and removed dev
  .github/workflows/post-process.yml
Labels: github_actions

#166 Update post-process.yml
  .github/workflows/post-process.yml
Labels: github_actions

#168 pin pytest>=7
  pyproject.toml
Labels: dependencies

#172 set minimum dependency versions
  pyproject.toml
Labels: dependencies

#173 Set mininum dependency versions, part 2
  pyproject.toml
Labels: dependencies

#174 set minimum pytest-cov dependency
  pyproject.toml
Labels: dependencies

#175 set minimum dependency versions
  pyproject.toml
Labels: dependencies

#176 set minimum dependency versions
  pyproject.toml
Labels: dependencies

#177 bump minimum scipy
  pyproject.toml
Labels: dependencies

#178 Revise 'Mixing Functions' documentation
  src/pyEQL/functions.py
  tests/test_functions.py
Labels: enhancement, docs
