Repository KingsburyLab/pyEQL, pull requests merged in 2024-03, with the labels that each got.

#112 Docs: cleanups per JOSS review
  CHANGELOG.md
  docs/amounts.md
  docs/arithmetic.md
  docs/chemistry.md
  docs/contributing.md
  docs/engines.md
  docs/index.md
  docs/installation.md
  docs/quickstart.md
  docs/serialization.md
  docs/units.md
  src/pyEQL/__init__.py
  src/pyEQL/activity_correction.py
  src/pyEQL/engines.py
  src/pyEQL/equilibrium.py
  src/pyEQL/functions.py
  src/pyEQL/logging_system.py
  src/pyEQL/salt_ion_match.py
  src/pyEQL/solute.py
  src/pyEQL/solution.py
  src/pyEQL/utils.py
  tests/test_solution.py
Labels: fix, docs

#113 alpha: fix incorrect calculation
  CHANGELOG.md
  src/pyEQL/equilibrium.py
  tests/test_equilibrium.py
Labels: release:minor, fix

#111 Testing, documentation, and exception handling for Apple Silicon
  .github/workflows/post-process.yml
  .github/workflows/testing.yaml
  CHANGELOG.md
  docs/engines.md
  docs/installation.md
  src/pyEQL/engines.py
  src/pyEQL/solution.py
  src/pyEQL/utils.py
  tests/test_activity.py
  tests/test_functions.py
  tests/test_phreeqc.py
  tests/test_salt_matching.py
  tests/test_solution.py
Labels: enhancement, release:minor, github_actions

#117 Solution: fixes failures when oxi state is unknown
  .pre-commit-config.yaml
  CHANGELOG.md
  src/pyEQL/solute.py
  src/pyEQL/solution.py
  tests/test_solution.py
Labels: fix, pkg

#118 NativeEOS: ensure equilibrate does not change solvent mass
  CHANGELOG.md
  src/pyEQL/engines.py
  tests/test_phreeqc.py
Labels: release:minor, fix

#120 Solution.get_total_amount: fix error on ppm unit
  CHANGELOG.md
  src/pyEQL/solution.py
  src/pyEQL/utils.py
Labels: release:patch, fix

#119 Overhaul logging system
  CHANGELOG.md
  docs/examples/pyeql_demo.ipynb
  docs/examples/pyeql_tutorial_database.ipynb
  docs/examples/pyeql_tutorial_osmotic_pressure.ipynb
  src/pyEQL/__init__.py
  src/pyEQL/activity_correction.py
  src/pyEQL/engines.py
  src/pyEQL/equilibrium.py
  src/pyEQL/functions.py
  src/pyEQL/logging_system.py
  src/pyEQL/salt_ion_match.py
  src/pyEQL/solute.py
  src/pyEQL/solution.py
  src/pyEQL/utils.py
  tests/test_logging.py
  tests/test_phreeqc.py
Labels: enhancement

#121 remove deprecated methods
  CHANGELOG.md
  src/pyEQL/functions.py
  src/pyEQL/solution.py
Labels: breaking, release:major

#124 Fix a missing close parenthesis in docstring
  src/pyEQL/equilibrium.py
Labels: docs
